version: "3"

services:
  server:
    build: "./serveur/areaAPI/"
    restart: always
    ports:
      - "8080:8080"
    networks:
      - back-net
    environment:
      - DB_HOST=db
      - PORT=8080
    depends_on:
      - db
  timer:
    build: "./serveur/timerService/"
    restart: always
    networks:
      - back-net
    depends_on:
      - db
  db:
    build: "./serveur/db/"
    restart: always
    networks:
      - back-net
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - DB_PORT=5432

  frontend:
    build: "./client_web"
    restart: always
    ports:
      - "8081:3000"
    networks:
      - back-net

networks:
  back-net:
    driver: bridge

volumes:
  db-data: